### PR TITLE
Creating pull request

### PR DESCRIPTION
**Pull request by jenn-codes**

### CODE REVIEW

**Comment by jonathan-irvin** [comment]
This commit: [here](https://github.com/jenn-codes/shopping-cart/commit/e48ca049cd98f6a89a20053b3da0ff1c0e4ede98)

Good use of the "body" in git commits, but next time split the changes into separate commits. Ideally, find a middle ground between committing when you save a file and when you finish a "feature" or fix a "bug".

When trying something new, make a branch. If you end up keeping the work, merge it, or in GH you can open a PR.

If it doesn't work, you can just leave the branch or delete it altogether.

**Comment by jonathan-irvin** [comment]
Tried to run locally. Seems you are missing your public folder.

**Comment by jonathan-irvin** [comment]
Screen Shot 2022-08-15 at 11 45 37 AM

**Comment by jenn-codes** [comment]
Added the public folder.

**Comment by jonathan-irvin** [comment]
So, it's looking good on the surface. Be mindful of your Lint warnings:
Screen Shot 2022-08-16 at 11 44 36 AM

**Pull request merged**
